### ISSUE TITLE
small option causes cb is not a function

### ISSUE THREAD

**Issue by coolaj86** [gtanner/qrcode-terminal#17]
```javascript
    qrcode.generate(url, { small: true }, function (qr) {
      console.log(qr);
    });
```

```
TypeError: cb is not a function
    at Object.module.exports.generate (/Users/user/Code/qrcode-terminal/lib/main.js:36:17)
```

**Comment by coolaj86** [comment]
looks like it just needs the new version to be published

**Comment by victorgama** [comment]
Same here. Would you mind to publish the update to npm, @gtanner?

**Comment by reverland** [comment]
Yaeh, waiting for an update on npmjs

**Comment by aurelienlewin** [comment]
Any update ?

**Comment by F-happy** [comment]
There is no update?

**Comment by feit** [comment]
@gtanner

**Comment by djMax** [comment]
Seems like it's time to fork and publish...

**Comment by mwbrooks** [comment]
Hey all, looks like I'm still listed as a npm maintainer and Github contributor on this repo. I'll try to publish the latest version tomorrow (and fix the callback error if it's not already in master).

We should consider adding someone else from the community to help with future work! :)

**Comment by mwbrooks** [comment]
Hi everyone, I've npm published the latest version, which includes the small qrcode:

```
qrcode-terminal@0.11.0
```

Sorry about the delay!
