### ISSUE TITLE
add feature to pipe stdin

### ISSUE THREAD

**Issue by defunctzombie** [gtanner/qrcode-terminal#18]
Makes it super easy to pipe something and get a qr code:

`echo 'foobar' | qrcode-terminal`

This is useful if you have a command that outputs something you want to scan with a mobile phone.

**Comment by defunctzombie** [comment]
For now I have a simple script that just uses this lib (https://github.com/defunctzombie/qr) but given that you already have a CLI tool I figured it would be nice for it to support this :)

**Comment by JustGreg** [comment]
you can also use this command (its not a pipe, just a workaround):

`qrcode-terminal "$(echo 'foobar')"`
or
`qrcode-terminal "$(cat file.txt)"`

**Comment by adius** [comment]
Yes, please!

**Comment by defunctzombie** [comment]
Fair.

**Comment by mwbrooks** [comment]
#19 added this functionality. It's published on npm as qrcode-terminal@0.12.0
https://www.npmjs.com/package/qrcode-terminal
