### ISSUE TITLE
qrencode broken in kvm/qemu vnc terminal/console

### ISSUE THREAD

**Issue by devZer0** [gtanner/qrcode-terminal#55]
hello, 

when trying to use qrencode in linux console in proxmox remote console (which is vnc connection to qemu framebuffer), with debian buster, bullseye and bookworm, i'm getting no useable output from qrencode

it just prints some "diamonds" for some chars, regardless what params i try. 

what could be causing this ?

<img width="307" alt="grafik" src="https://github.com/gtanner/qrcode-terminal/assets/3506105/7814fd93-94e5-4381-9eb9-54dc6d849dad">

here is some similar report to it:
https://www.reddit.com/r/Proxmox/comments/xo1s79/ubuntu_vm_within_proxmox_issue_renderingviewing/

**Comment by devZer0** [comment]
also see discussion/findings at https://forum.proxmox.com/threads/qrencode-is-broken-in-proxmox-kvm-qemu-vnc-console.134104/

**Comment by devZer0** [comment]
apparently, linux console can't handle special chars like this. 

is there a way to have readable qrcode in console which is not taking too much space? ascii is far to large to fit in a console

**Comment by lnxbil** [comment]
Ehhhmmm, I just realized this now, but you're talking about`qrencode` and not `qrcode-terminal`. This project here is `qrcode-terminal` and it works perfectly in PVE:

![grafik](https://github.com/gtanner/qrcode-terminal/assets/727711/0a7efc3d-0e7e-44d1-8583-1c5d28b3ca16)

Whereas `qrencode` does indeed not work with `utf8`, but with `andi256`:

![grafik](https://github.com/gtanner/qrcode-terminal/assets/727711/0a5f2ed3-eb8e-4f90-8606-8c13979bdb91)

**Comment by devZer0** [comment]
eeek. sorry, i did a google search for qrencode github issues and was in a hurry, so i did oversee, that this is a completely different project

yes, i know of ascii/ansi mode options, but the pivpn/wireguard qrcode won't fit into console with that

**Comment by devZer0** [comment]
sorry for the noise. closing.

**Comment by lnxbil** [comment]
> yes, i know of ascii/ansi mode options, but the pivpn/wireguard qrcode won't fit into console with that

use a smaller font, `dpkg-reconfigure console-setup` or bigger framebuffer size.
