### ISSUE TITLE
Is it possible to customize the size of the qrcode?

### ISSUE THREAD

**Issue by hirokith** [gtanner/qrcode-terminal#9]
Currently the size for the generated qrcode is too big, is it possible to customize its size? Thank you!

**Comment by schoenwaldnils** [comment]
How about generating an svg instead, and displaying it with ImageMagick?

**Comment by CodeMan99** [comment]
@schoenwaldnils The README of this project links to node-qrcode, which has the ability to generate an [image file](https://github.com/soldair/node-qrcode#tofilepath-text-options-cberror).
